# Usar la imagen oficial de Python como base
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY requirements.txt requirements.txt
COPY app.py app.py
# Copiar el archivo token.json al directorio de trabajo en el contenedor
COPY token.json token.json

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto donde correrá la API
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["python", "app.py"]